version: 2.1
jobs:
  binary_convert_testing:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: cd Projects/binary_converter
      - run: flutter doctor
      - run: flutter test --verbose --coverage
workflows:
  version: 2
  binary_convert:
    jobs:
      - binary_convert_testing
